# Generated by Django 4.2.27 on 2026-01-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_alter_userrole_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
