# Generated by Django 5.2.8 on 2026-01-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_studentprofile_avatar_teacherprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
