# Generated by Django 4.2.27 on 2026-01-16 20:54

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='preview_video_url',
        ),
        migrations.RemoveField(
            model_name='course',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='courselesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.course_thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=courses.models.course_thumbnail_upload_path),
        ),
        migrations.AddField(
            model_name='courselesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.lesson_video_upload_path),
        ),
    ]
