# Generated by Django 5.2.8 on 2026-02-15 04:00

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_teachersubjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=courses.models.course_thumbnail_upload_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=courses.models.course_thumbnail_upload_path),
        ),
    ]
