# Generated by Django 5.1.5 on 2026-02-04 12:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issue_date',
            new_name='issued_date',
        ),
    ]