# Generated by Django 5.2.8 on 2026-02-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_issue_date_field'),
    ]

    operations = [
    ]
