# Generated by Django 5.2.8 on 2026-04-05 04:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_livecall_archived_by_initiator_and_newslettersubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking', 'Booking'), ('message', 'Message'), ('call', 'Call'), ('payment', 'Payment'), ('assessment', 'Assessment'), ('system', 'System'), ('promotion', 'Promotion')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='livecallparticipant',
            index=models.Index(fields=['live_call', 'user'], name='notificatio_live_ca_bc676b_idx'),
        ),
        migrations.AddIndex(
            model_name='livecallparticipant',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_7253e4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'deleted_by_receiver', 'is_read'], name='notificatio_receive_fdaf80_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'deleted_by_sender', 'created_at'], name='notificatio_sender__901312_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='notificatio_created_5a3e36_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
    ]
